#pragma once

#include "../../libs/json.hpp"
#include "cli.hpp"
#include "constants.hpp"
#include "geometry/geometry.hpp"
#include "geometry/sphere.hpp"
#include "geometry/box.hpp"
#include "geometry/plane.hpp"
#include "geometry/geometry_list.hpp"
#include "material/material.hpp"
#include "scene.hpp"
#include "ray/color.hpp"
#include "ray/ray.hpp"
#include "camera.hpp"
#include "reader.hpp"
#include "utils/file_writer.hpp"
