#pragma once

#include "camera.hpp"
#include "cli.hpp"
#include "constants.hpp"
#include "geometry/geometry.hpp"
#include "geometry/geometry_list.hpp"
#include "geometry/sphere.hpp"
#include "material/material.hpp"
#include "material/texture.hpp"
#include "ray/color.hpp"
#include "ray/hittable.hpp"
#include "ray/ray.hpp"
#include "ray/light_source.hpp"
#include "reader.hpp"
#include "utils/file_writer.hpp"
